# Generated by Django 5.1.7 on 2025-03-08 19:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('plant_App', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='username',
            field=models.CharField(max_length=100),
        ),
    ]
